package com.example.ShoppingListLinda;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.web.servlet.support.SpringBootServletInitializer;

//this code is auto generated by the https://start.spring.io/ Spring Intializr
//(and then edited to add the extension which should allow it to create a WAR file)
//The shopping list is contains items that are stored in an H2 in memory database
//These items are accessed via JPA
//This is wrapped in the Spring MVC layer so that it can be accessed over the internet.

//This project was done following the https://spring.io/guides/tutorials/rest/ tutorial
//Spring Boot Project set up with https://start.spring.io/ and imported into Eclipse with Maven
//Tested with Postman (for GET, POST, PUT, DELETE statements)

@SpringBootApplication
public class ShoppingListLindaApplication extends SpringBootServletInitializer{

	public static void main(String[] args) {
		SpringApplication.run(ShoppingListLindaApplication.class, args);
	}

}
